import type { SeoRule } from "./types";

/**
 * The technical-SEO rule catalog. In the MVP these are descriptors that
 * power the marketing copy and document the engine's coverage; each will
 * gain an `evaluate()` implementation as the real crawler lands. They map
 * one-to-one to the categories in the audit UI.
 */
export const SEO_RULES: SeoRule[] = [
  {
    id: "meta.title.missing",
    category: "metadata",
    title: "Missing or duplicate <title>",
    description: "Every indexable page should have a unique, descriptive title.",
    defaultImpact: "high",
    defaultEffort: "low",
    defaultRisk: "low",
    canAutoFix: true,
    frameworks: ["nextjs", "nuxt", "astro", "remix"],
  },
  {
    id: "meta.description.missing",
    category: "metadata",
    title: "Missing meta description",
    description: "Pages without a description get an auto-generated SERP snippet.",
    defaultImpact: "medium",
    defaultEffort: "medium",
    defaultRisk: "low",
    canAutoFix: true,
  },
  {
    id: "meta.og.image.missing",
    category: "metadata",
    title: "Missing OpenGraph image",
    description: "Shared links render without a preview card.",
    defaultImpact: "medium",
    defaultEffort: "low",
    defaultRisk: "low",
    canAutoFix: true,
    frameworks: ["nextjs"],
  },
  {
    id: "indexing.canonical.missing",
    category: "indexing",
    title: "Missing or inconsistent canonical",
    description: "Duplicate URLs split ranking signals without a canonical.",
    defaultImpact: "high",
    defaultEffort: "low",
    defaultRisk: "low",
    canAutoFix: true,
  },
  {
    id: "indexing.sitemap.incomplete",
    category: "indexing",
    title: "Sitemap missing dynamic routes",
    description: "Dynamic pages absent from the sitemap are discovered slowly.",
    defaultImpact: "critical",
    defaultEffort: "medium",
    defaultRisk: "medium",
    canAutoFix: true,
    frameworks: ["nextjs", "nuxt", "astro"],
  },
  {
    id: "indexing.robots.stale",
    category: "indexing",
    title: "robots.txt references stale sitemap",
    description: "A broken Sitemap directive sends crawlers to a 404.",
    defaultImpact: "high",
    defaultEffort: "low",
    defaultRisk: "low",
    canAutoFix: true,
  },
  {
    id: "structure.h1.multiple",
    category: "structure",
    title: "Multiple or missing H1",
    description: "Each page should have exactly one primary heading.",
    defaultImpact: "medium",
    defaultEffort: "low",
    defaultRisk: "low",
    canAutoFix: true,
  },
  {
    id: "structure.headings.skipped",
    category: "structure",
    title: "Skipped heading levels",
    description: "Jumping heading levels breaks the document outline.",
    defaultImpact: "low",
    defaultEffort: "low",
    defaultRisk: "low",
    canAutoFix: true,
  },
  {
    id: "images.alt.missing",
    category: "images",
    title: "Images without alt text",
    description: "Missing alt hurts accessibility and image search.",
    defaultImpact: "medium",
    defaultEffort: "high",
    defaultRisk: "low",
    canAutoFix: true,
  },
  {
    id: "schema.article.missing",
    category: "schema",
    title: "Missing Article schema",
    description: "Blog/MDX content without Article structured data.",
    defaultImpact: "high",
    defaultEffort: "medium",
    defaultRisk: "low",
    canAutoFix: true,
    frameworks: ["astro", "mdx", "nextjs"],
  },
  {
    id: "schema.product.missing",
    category: "schema",
    title: "Missing Product/Offer schema",
    description: "Pricing pages without Product data miss price-rich results.",
    defaultImpact: "high",
    defaultEffort: "medium",
    defaultRisk: "low",
    canAutoFix: true,
  },
  {
    id: "linking.orphans",
    category: "internal-linking",
    title: "Orphan pages",
    description: "Pages with no internal inbound links accrue no authority.",
    defaultImpact: "medium",
    defaultEffort: "medium",
    defaultRisk: "low",
    canAutoFix: false,
  },
  {
    id: "linking.weak-anchors",
    category: "internal-linking",
    title: "Weak anchor text",
    description: "Generic anchors pass little topical signal.",
    defaultImpact: "low",
    defaultEffort: "low",
    defaultRisk: "low",
    canAutoFix: true,
  },
  {
    id: "performance.render-blocking",
    category: "performance",
    title: "Render-blocking resources",
    description: "Heavy synchronous scripts delay first paint.",
    defaultImpact: "medium",
    defaultEffort: "medium",
    defaultRisk: "medium",
    canAutoFix: false,
  },
  {
    id: "framework.metadata-api",
    category: "framework",
    title: "Underused framework metadata API",
    description: "generateMetadata / useSeoMeta not used on dynamic routes.",
    defaultImpact: "medium",
    defaultEffort: "medium",
    defaultRisk: "low",
    canAutoFix: true,
    frameworks: ["nextjs", "nuxt", "remix", "sveltekit"],
  },
];

export function getRule(id: string): SeoRule | undefined {
  return SEO_RULES.find((r) => r.id === id);
}
